research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant scientific papers
    the current year is {current_year}.
  expected_output: >
    A list with 3 to 5 of the most relevant scientific paper about {topic}.
    With each paper, include the title, author(s), publication date, and direct link or way to access the paper.
    Do no add any extra or unnecessary commentary.
  agent: researcher

writing_task:
  description: >
    Review the context you got and create a full report based on the provided scientific papers.
    Do not create a section for each paper, instead use the information from all of the papers
    combined to create your report.
    Make sure the report is detailed and contains any and all relevant information to {topic}.
    Assume that the reader of your report does not know much about the topic, so explain
    systems that they would not be familliar with.
    Do not use information that is not given from the research papers.
  expected_output: >
    A fully fledged report about {topic} with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: writer

design_task:
  description: >
    Review the context you got and section the report into groups as needed.
    Create citations for all of the scientific papers at the end of the report.
    Do not add or change any information in the report.
  expected_output: >
    A fully fledged report about {topic} sectioned into groups, each with a full section of information.
    A single list of citations at the end of the report.
    The whole paper in chicago formatting.
    Formatted as markdown without '```'
  agent: designer